PZ1Sharer05/CBL

cbl.py
This time it adds a new unit conversion function that allows to convert units from meter to centimeter and vise versa. It still needs the other units and we will solve that later.
=> Unit Conversion

cbl.py
We removed the pi and full pi variables as we it to be in a supporting files library.
=> Removed pi and fullpi

cbl.py
We have removed all of the Math functions because we are going to put it in a separate library that is going to be released in a later time for version 2.0.
=> Removed all Math Functions

cblmath.py
We added the math module and we will add more conversions and variables in the further time when version 2.0 is going to be released
=> Added Math Module

Libs
Some description of the CBL Standard libs.
=> CBL Library Description

cbl.py
We combined the upper and lower function to a single function called changeSizeOfWord
=> Removed the uppercase or lowercase function

cbl.py
We just changed some of the name of functions so that the name is much easier to learn and remember.
=> Changed some of the names of functions

cbl.py
We cleared some bugs in the code and also added a count feature.
=> Cleared some errors in code

cbl.py
Some more functions that are helpful and useful.
=> Added more functions for next Version

cbl.py
We added a new randomly take numbers function that uses the random module to take random numbers.
=> New Random Take Numbers function

cblmath.py
We added more functions and fixed some bugs.
=> Added more Math related functions in CBL Math Module

cblmath.py
We added a calculate area function to calculate the area of shapes.
=> Added more math functions

cblmath.py
We added more math related functions for the math lib
=> Cblmath new functions

cblmath.py
We added some more math functions to the math lib.
=> CBL Math Library

cblmath.py
We added new math related functions for 1.2
=> Added new math functions

cblmath.py
We added the new argument that allows you to choose the types of shapes.
=> Added new arguments for functions 

cblmath.py
We merged the circle area and perimeter properties.
=> Circle Area and Perimeter Merged

cblmath.py
We merged the square and rectangle function to a single function.
=> Merged Square and Rectangle

cbl.py
We changed the some of the functions to use return instead of print.
=> Replacement of print with return

cblmath.py
We merged some of the functions to one single function with more parameters.
=> Merged functions

cbl.py
Changed display() to showText() and showShortText().
=> Changed display to 2 new seperate functions.

cbl.py
Cleaning Code to make it look neater.
=> Cleaning Code to make it look neater

cbl.py
We changed the name of functions.
=> Changed name of functions

cbl.py
Removed the askWithAnswer() function
=> Removed the askWithAnswer() function

cbl.py
=> Added new functions

cbl.py
=> Changed changeSizeOfWord() to sizeOfWord()

How to Install
=> Update How to Install
